version: "3.9" 

services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: elasticsearch-container
    network_mode: host
    environment:
      cluster.name: elasticsearch-cluster
      network.host: 0.0.0.0
      bootstrap.memory_lock: 'true'
      discovery.type: single-node
      ELASTIC_CONTAINER: 'true'
    volumes:
      - ~/DevOps/elasticsearch/data:/usr/share/elasticsearch/data:rw