version: '3'

services:
  redis:
    image: "redis"
    container_name: "redis-container"
    #restart: always
    ports:
      - "6379:6379"
    # environment:
    #   - REDIS_PASSWORD=mysecretpassword
    volumes:
      #- ${PWD}/DevOps/docker-commpose/redis/data/:/data
      - C:\Users\lukas\source\repos\DevOps\docker-compose\redis\data:/data
      - C:\Users\lukas\source\repos\DevOps\docker-compose\redis\config\redis.conf:/usr/local/etc/redis/redis.conf
      #- ${PWD}/DevOps/docker-commpose/redis/:/usr/local/etc/redis/redis.conf