version: '3'

services:
  mongodb:
    image: mongo
    container_name: "mongo-container"
    restart: unless-stopped
    hostname: mongodb 
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=test
    volumes:
      # - ${PWD}/DevOps/docker-compose/mongodb/data/:/data/db
      - C:\Users\lukas\source\repos\DevOps\docker-compose\mongodb\data:/data/db
  mongo-express:
    image: mongo-express
    container_name: "mongo-express-container"
    restart: unless-stopped
    links: 
      - mongodb
    depends_on:  
      - mongodb
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=passPass
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongodb:27017/