version: '3'

services:
  rabbit:
    image: "rabbitmq:3-management"
    container_name: "rabbit-container"
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=maksimus
    volumes:
      # - ${PWD}/DevOps/docker-compose/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
      - C:\Users\lukas\source\repos\DevOps\docker-compose\rabbitmq\data:/var/lib/rabbitmq/mnesia/